# Generated by Django 3.2.12 on 2022-03-08 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('isin', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('value', models.FloatField()),
                ('ter', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etf_manager.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etf_manager.currency')),
                ('distribution_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etf_manager.distributionpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etf_manager.etf')),
                ('trading_platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etf_manager.tradingplatform')),
            ],
        ),
        migrations.AddField(
            model_name='etf',
            name='geography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etf_manager.geography'),
        ),
        migrations.AddField(
            model_name='etf',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etf_manager.sector'),
        ),
        migrations.AddField(
            model_name='etf',
            name='tags',
            field=models.ManyToManyField(to='etf_manager.Tag'),
        ),
    ]
