# Generated by Django 3.2.12 on 2022-03-08 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etf_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='distributionpolicy',
            options={'verbose_name_plural': 'Distribution Policies'},
        ),
        migrations.AlterModelOptions(
            name='etf',
            options={'ordering': ['category', 'isin']},
        ),
        migrations.AlterModelOptions(
            name='geography',
            options={'verbose_name_plural': 'Geographies'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='tradingplatform',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='etf',
            name='category',
            field=models.ForeignKey(help_text='Select ETF Category', on_delete=django.db.models.deletion.PROTECT, to='etf_manager.category'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='currency',
            field=models.ForeignKey(help_text='Select ETF Currency', on_delete=django.db.models.deletion.PROTECT, to='etf_manager.currency'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='distribution_policy',
            field=models.ForeignKey(help_text='Select ETF distribution policy', on_delete=django.db.models.deletion.PROTECT, to='etf_manager.distributionpolicy'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='geography',
            field=models.ForeignKey(help_text='Select ETF Geography', on_delete=django.db.models.deletion.PROTECT, to='etf_manager.geography'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='isin',
            field=models.CharField(help_text='Enter ETF ISIN', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etf',
            name='location',
            field=models.CharField(help_text='Enter ETF location', max_length=50),
        ),
        migrations.AlterField(
            model_name='etf',
            name='manager',
            field=models.CharField(help_text='Enter ETF manager', max_length=100),
        ),
        migrations.AlterField(
            model_name='etf',
            name='sector',
            field=models.ForeignKey(help_text='Select ETF Sector', on_delete=django.db.models.deletion.PROTECT, to='etf_manager.sector'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='size',
            field=models.IntegerField(help_text='Enter ETF size'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='tags',
            field=models.ManyToManyField(help_text='Select ETF tags', to='etf_manager.Tag'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='ter',
            field=models.FloatField(help_text='Enter ETF TER'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='ticker',
            field=models.CharField(help_text='Enter ETF Ticker', max_length=10),
        ),
        migrations.AlterField(
            model_name='etf',
            name='value',
            field=models.FloatField(help_text='Enter ETF current value'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['updated_at', 'etf'], name='etf_manager_updated_17d4ff_idx'),
        ),
    ]
