# Generated by Django 3.2.12 on 2022-03-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etf_manager', '0002_auto_20220308_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(help_text='Enter the category', max_length=20),
        ),
        migrations.AlterField(
            model_name='distributionpolicy',
            name='description',
            field=models.CharField(help_text='Enter the distribution policy', max_length=20),
        ),
        migrations.AlterField(
            model_name='etf',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'United States Dollars'), ('JPY', 'Japan Yen')], help_text='Select ETF Currency', max_length=3),
        ),
        migrations.AlterField(
            model_name='geography',
            name='description',
            field=models.CharField(help_text='Enter the geography', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='etf',
            field=models.ForeignKey(help_text='Select the ETF', on_delete=django.db.models.deletion.PROTECT, to='etf_manager.etf'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(help_text='Enter the current price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(help_text='Enter the quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trading_platform',
            field=models.CharField(choices=[('DEG', 'Degiro'), ('ING', 'ING Direct')], help_text='Select the trading platform', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='description',
            field=models.CharField(help_text='Enter the economic sector', max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(help_text='Enter the tag', max_length=50),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='TradingPlatform',
        ),
    ]
