# Generated by Django 3.2.12 on 2022-03-08 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('etf_manager', '0003_auto_20220308_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this order', primary_key=True, serialize=False, unique=True),
        ),
    ]
