# Generated by Django 3.2.12 on 2022-03-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf_manager', '0004_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Enter a description', max_length=200),
        ),
    ]
